version: 2
services:
  dev:
    environment:
      # list of github usernames whose SSH public keys to install for root user
      GITHUB_USERS_TO_ALLOW_SSH: 'user1 user2'

      # if given, will clone the named repo (git clone-able URL or github
      # project ID <user>/<project>) to /root/.dotfiles (unless there's already
      # a git repo located there), on startup, then run its './install.sh' if
      # exists
      DOTFILES_CLONE_URL: 'rtlong/dotfiles'

    ports:
      # set a forced (and more importantly stable) port number for SSH
      - '2222:22'
